### ISSUE TITLE
How to setup ConfigServer with Halyard for Vault?

### ISSUE THREAD

**Issue by dplummer** [spinnaker/spinnaker.github.io#1559]
I'm using Halyard to deploy spinnaker to kubernetes. I would like to store kubeconfig in Vault. I've read [External Account Configuration](https://www.spinnaker.io/setup/configuration/#configuration-files) and #5016, but it isn't clear where the Spring ConfigServer configuration goes when using Halyard.

I've got a `spinnakerconfig.yml` in `/opt/spinnaker` and `~/.hal/default/profiles/` with:

```
spring:
  profiles:
    include: vault
  cloud:
    vault:
      authentication: KUBERNETES
      kubernetes:
        role: spin-halyard
        kubernetes-path: kubernetes
        service-account-token-file: /var/run/secrets/kubernetes.io/serviceaccount/token
    config:
      server:
        vault:
          host: [vault host]
          port: 8200
          backend: secret
          kvVersion: 2
          default-key: [path to kubeconfigs in vault]
```

and my `~/.hal/config` has:
```
        kubernetes:
          accounts:
          - cacheThreads: 1
            cachingPolicies: []
            checkPermissionsOnStartup: false
            configureImagePullSecrets: false
            customResources: []
            dockerRegistries: []
            kinds: []
            kubeconfigFile: configserver:[name of key in vault that is in the default-key path]
            liveManifestCalls: true
            name: my-account
            namespaces:
            - [my-namespace]
            oauthScopes: []
            omitKinds: []
            omitNamespaces: []
            onlySpinnakerManaged: true
            permissions:
              EXECUTE:
              - spinnaker-admin
              READ:
              - spinnaker-admin
              WRITE:
              - spinnaker-admin
            providerVersion: V2
            serviceAccount: false
          enabled: true
          primaryAccount: my-account
```

in my `/opt/halyard/config/halyard.yml` I have:

```
halconfig:
  filesystem:
    path: ~/.hal/config
```

But when I run `hal deploy apply` I get:

```
+ Get current deployment
  Success
+ Prep deployment
  Success
+ Preparation complete... deploying Spinnaker
+ Get current deployment
  Success
- Apply deployment
  Failure
Problems in Global:
! ERROR Unexpected exception: java.lang.IllegalStateException:
  Failed to read kubeconfig file 'configserver:[my vault key]', but
  validation passed: Config Server repository not configured for resource
  "configserver:[my vault key]"
```

Where should I put the Spring ConfigServer config such that Halyard & Clouddriver know how its configured?
