### ISSUE TITLE
Halyard docs for mapping roles from OIDC in OAuth2 UserInfoMapping not clear.

### ISSUE THREAD

**Issue by shubhamc183** [spinnaker/spinnaker.github.io#1986]
Recently I was trying to setup Spinnaker for authN and authZ via Keycloak, OIDC where I wanted to map roles.

I faced an issue for quite a time setting the AuthZ for quite some time where I was not able to map roles from external sources.

`~/.hal/config`
```
security:
  basic:
    enabled: true
  user: {}
  oauth2:
    enabled: true
    client:
      clientId: XXX
      clientSecret: XXX
      accessTokenUri: XXX
      userAuthorizationUri: XXX
    resource:
      userInfoUri: XXX
    userInfoMapping: {}
    provider: OTHER
```

And `.hal/default/profiles/gate-local.yml`
```
security:
  oauth2:
    userInfoMapping:
      email: email
      firstName: given_name
      lastName: family_name
      username: preferred_username
      roles: groups
    client:
      scope: openid,spinroles

```
**The important detail here is that `userInfoMapping` I have to keep in `.hal/default/profiles/gate-local.yml` and not in `~/.hal/config`. Else it'll result into an error like this https://github.com/spinnaker/spinnaker/issues/5902#issue-655753819**

I was not able to find the exact documentation which states that, I spent like 10 days on this so opening an issue to document if not present already.

https://github.com/spinnaker/spinnaker/issues/5902
