### ISSUE TITLE
Gate: saml behind SSL terminating ELB requires extra settings

### ISSUE THREAD

**Issue by marshallbrekka** [spinnaker/spinnaker.github.io#263]
Page: /setup/security/authentication/saml/

Feedback:
When running Gate behind a load balancer that terminates SSL, you need to also specify the following settings, otherwise Gate redirects to an `http` url after successful auth.

```yaml
server:
  tomcat:
    protocolHeader: X-Forwarded-Proto
    remoteIpHeader: X-Forwarded-For
    internalProxies: .*
```

From ttomsu on `spin-auth` slack channel:
> I need to move the comment from the OAuth page to the network arch page
