### ISSUE TITLE
jenkins - igor configuration

### ISSUE THREAD

**Issue by nacho-milanese** [spinnaker/spinnaker.github.io#280]
Page: /guides/tutorials/codelabs/hello-deployment/

Feedback:

The jenkins configuration in the yml that worked for me was:

```
jenkins:
  enabled: true
  masters:
    -
      address: "https://spinnaker.cloudbees.com/"
      name: cloudbees
      password: f5e182594586b86687319aa5780ebcc5
      username: spinnakeruser
```

as mentioned in the page  https://github.com/spinnaker/igor, and **not the mentioned here**.

In order to make it work I had to **disable** the "Prevent Cross Site Request Forgery exploits" option in jenkins security configuration.

It all worked configuring the igor yml directly, not using halyard command as it creates a non working config.
