### ISSUE TITLE
External redis - custom gate config

### ISSUE THREAD

**Issue by celamb4** [spinnaker/spinnaker.github.io#986]
Following official documentation (https://www.spinnaker.io/setup/productionize/caching/externalize-redis/) the only required config would be 

> overrideBaseUrl: $REDIS_ENDPOINT
> skipLifeCycleManagement: true

However, gate fails to initialize. Found an issue with the fix. Instructions need to be updated to reflect required conf.

https://github.com/spinnaker/spinnaker/issues/1309#issuecomment-260971228

```
redis:
    configuration:
         secure:
              true
```
